export enum AVALON_CHARACTERS {
  MERLIN = 'merlin',
  PERCIVAL = 'percival',
  MORDRED = 'mordred',
  MORGANA = 'morgana',
  OBERON = 'oberon',
  ASSASSIN = 'assassin',
  KNIGHT = 'knight', // good guy
  MINION = 'minion' // bad guy
}

enum AVALON_ALLEGIANCE {
  GOOD = 'good',
  EVIL = 'evil'
}


type AvalonCharacter = {
  allegiance: AVALON_ALLEGIANCE;
  role: AVALON_CHARACTERS;
  sees: AVALON_CHARACTERS[];
};

export const avalonCharacters: Record<AVALON_CHARACTERS, AvalonCharacter> = {
  [AVALON_CHARACTERS.MERLIN]: {
    allegiance: AVALON_ALLEGIANCE.GOOD,
    role: AVALON_CHARACTERS.MERLIN,
    sees: [
      AVALON_CHARACTERS.MORGANA,
      AVALON_CHARACTERS.ASSASSIN,
      AVALON_CHARACTERS.OBERON,
      AVALON_CHARACTERS.MINION
    ]
  },
  [AVALON_CHARACTERS.PERCIVAL]: {
    allegiance: AVALON_ALLEGIANCE.GOOD,
    role: AVALON_CHARACTERS.PERCIVAL,
    sees: [
      AVALON_CHARACTERS.MERLIN,
      AVALON_CHARACTERS.MORGANA
    ]
  },
  [AVALON_CHARACTERS.MORDRED]: {
    allegiance: AVALON_ALLEGIANCE.EVIL,
    role: AVALON_CHARACTERS.MORDRED,
    sees: [
      AVALON_CHARACTERS.MORGANA,
      AVALON_CHARACTERS.ASSASSIN,
      AVALON_CHARACTERS.MINION
    ]
  },
  [AVALON_CHARACTERS.MORGANA]: {
    allegiance: AVALON_ALLEGIANCE.EVIL,
    role: AVALON_CHARACTERS.MORGANA,
    sees: [
      AVALON_CHARACTERS.ASSASSIN,
      AVALON_CHARACTERS.MORDRED,
      AVALON_CHARACTERS.MINION
    ]
  },
  [AVALON_CHARACTERS.OBERON]: {
    allegiance: AVALON_ALLEGIANCE.EVIL,
    role: AVALON_CHARACTERS.OBERON,
    sees: []
  },
  [AVALON_CHARACTERS.ASSASSIN]: {
    allegiance: AVALON_ALLEGIANCE.EVIL,
    role: AVALON_CHARACTERS.ASSASSIN,
    sees: [
      AVALON_CHARACTERS.MORGANA,
      AVALON_CHARACTERS.MORDRED,
      AVALON_CHARACTERS.MINION
    ]
  },
  [AVALON_CHARACTERS.KNIGHT]: {
    allegiance: AVALON_ALLEGIANCE.GOOD,
    role: AVALON_CHARACTERS.KNIGHT,
    sees: []
  },
  [AVALON_CHARACTERS.MINION]: {
    allegiance: AVALON_ALLEGIANCE.EVIL,
    role: AVALON_CHARACTERS.MINION,
    sees: [
      AVALON_CHARACTERS.MORGANA,
      AVALON_CHARACTERS.MORDRED,
      AVALON_CHARACTERS.ASSASSIN
    ]
  }
};

export const numPlayersToRoles = {
  5: [AVALON_CHARACTERS.MERLIN, AVALON_CHARACTERS.PERCIVAL,AVALON_CHARACTERS.KNIGHT, AVALON_CHARACTERS.MORGANA, AVALON_CHARACTERS.ASSASSIN],
  6: [AVALON_CHARACTERS.MERLIN, AVALON_CHARACTERS.PERCIVAL, AVALON_CHARACTERS.KNIGHT, AVALON_CHARACTERS.KNIGHT, AVALON_CHARACTERS.MORGANA, AVALON_CHARACTERS.ASSASSIN],
  7: [AVALON_CHARACTERS.MERLIN, AVALON_CHARACTERS.PERCIVAL, AVALON_CHARACTERS.KNIGHT, AVALON_CHARACTERS.KNIGHT, AVALON_CHARACTERS.MORGANA, AVALON_CHARACTERS.ASSASSIN, AVALON_CHARACTERS.OBERON],
  8: [AVALON_CHARACTERS.MERLIN, AVALON_CHARACTERS.PERCIVAL, AVALON_CHARACTERS.KNIGHT, AVALON_CHARACTERS.KNIGHT, AVALON_CHARACTERS.KNIGHT, AVALON_CHARACTERS.MORGANA, AVALON_CHARACTERS.ASSASSIN, AVALON_CHARACTERS.OBERON],
  9: [AVALON_CHARACTERS.MERLIN, AVALON_CHARACTERS.PERCIVAL, AVALON_CHARACTERS.KNIGHT, AVALON_CHARACTERS.KNIGHT, AVALON_CHARACTERS.KNIGHT, AVALON_CHARACTERS.MORGANA,  AVALON_CHARACTERS.ASSASSIN, AVALON_CHARACTERS.OBERON, AVALON_CHARACTERS.MINION],
  10: [AVALON_CHARACTERS.MERLIN, AVALON_CHARACTERS.PERCIVAL, AVALON_CHARACTERS.KNIGHT, AVALON_CHARACTERS.KNIGHT, AVALON_CHARACTERS.KNIGHT, AVALON_CHARACTERS.KNIGHT, AVALON_CHARACTERS.MORGANA, AVALON_CHARACTERS.ASSASSIN, AVALON_CHARACTERS.OBERON, AVALON_CHARACTERS.MORDRED],
  11: [AVALON_CHARACTERS.MERLIN, AVALON_CHARACTERS.PERCIVAL, AVALON_CHARACTERS.KNIGHT, AVALON_CHARACTERS.KNIGHT, AVALON_CHARACTERS.KNIGHT, AVALON_CHARACTERS.KNIGHT, AVALON_CHARACTERS.KNIGHT, AVALON_CHARACTERS.MORGANA, AVALON_CHARACTERS.ASSASSIN, AVALON_CHARACTERS.OBERON, AVALON_CHARACTERS.MORDRED],
}